version: "3.7"

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./web:/usr/share/nginx/html/
    links:
      - wp
    restart: always

  wp:
    image: wordpress:5.8.2-fpm
    restart: alaways
    ports:
      - 9000:9000
    volume:
      - ./web:/var/www/html

  
